import os
import json
from pathlib import Path
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter, Namespace
from typing import Any, Dict, List, Union
from logging import RootLogger
from multiprocessing import cpu_count
from functools import partial

from datasets import Dataset, DatasetDict, load_from_disk, enable_progress_bars, disable_progress_bars
from jinja2 import Environment, FileSystemLoader, Template

from partages_llm.utils import basic_logger_init, make_version_subdir_path
from partages_llm.processing import instruction_to_prompt_completion

DESC="Transforms an MCQA dataset as generated by `instruction_pipeline_processing_base.py` into inference-ready sets of prompts"
TTT_HELP="Target task for the output dataset: either icl (In-Context Learning; evaluation-only, with prompting examples) "\
"or sft (Supervised Fine-Tuning; training and validation sets)"
MAPBS_HELP="Set this to a value >1 to do a batched application of the prompt generation function"
DYNAMICTEMPLATE_HELP="Path to a .jinja template for MEDIQAL - prompts change as a function of the speciality and the number of correct answers"
FIXEDTEMPLATE_HELP="Path to a .txt file for FrenchMedMCQA - same prompt for every question "
RESAMPLE_HELP="This only applies when `target_task_type==icl` and `nshot>0`; by default, the `nshot` examples to use for few-shot "\
"prompting are sampled only once from the training set and then used for every prompt - this flag causes a new set of examples to "\
"be sampled for each prompt"


def parse_arguments() -> Namespace:
    here = os.path.dirname(__file__)
    config_dir = os.path.normpath(
        os.path.join(
            here, *[os.pardir] * 2, "configs", "templates", "mcqa-processing"
        )
    )
    default_template_path_instruction_dynamic = os.path.join(
        config_dir, "mediqal-instructions-v0.jinja"
    )
    default_template_path_instruction_fixed = os.path.join(
        config_dir, "fmcqa-instruction-v0.txt"
    )
    default_template_path_fewshot = os.path.join(
        config_dir, "wp2-instructions-fewshot-interstitial.jinja"
    )
    default_num_workers = cpu_count() // 2
    default_data_dir = os.path.join(os.getenv("HOME"), "partages-llm-data/mcqa/preproc")

    parser = ArgumentParser(description=DESC, formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument("target_task_type", choices={"icl", "sft"}, help=TTT_HELP)
    parser.add_argument("-v", "--dataset-version", type=int, default=0, help=MAPBS_HELP)
    parser.add_argument("-n", "--nshot", type=int, default=5)
    parser.add_argument("-m", "--max-word-count", type=int)
    parser.add_argument("-w", "--workers", type=int, default=default_num_workers)
    parser.add_argument("-b", "--map-bs", type=int, default=1, help=MAPBS_HELP)
    parser.add_argument(
        "-i", "--template-path-instruction-dynamic",
        default=default_template_path_instruction_dynamic,
        help=DYNAMICTEMPLATE_HELP
    )
    parser.add_argument(
        "-t", "--template-path-instruction-fixed",
        default=default_template_path_instruction_fixed,
        help=FIXEDTEMPLATE_HELP
    )
    parser.add_argument("-f", "--template-path-fewshot", default=default_template_path_fewshot)
    parser.add_argument("-r", "--resample", action="store_true", help=RESAMPLE_HELP)
    parser.add_argument("--dd", dest="ds_dir", default=default_data_dir)
    parser.add_argument("--seed", type=int, default=13579)
    return parser.parse_args()


def get_instruction_template(template_path: str) -> Template:
    """
    Utility function for Jinja2 templates.
    """
    jinja_env_dir, template_file_name = os.path.split(template_path)
    jinja_env = Environment(loader=FileSystemLoader(jinja_env_dir))
    return jinja_env.get_template(template_file_name)


def filter_func(x: Dict[str, Any], source: str, split: str="validation") -> bool:
    """
    Returns a boolean inclusion indicator based on the metadata arguments provided. 
    """
    sourcecheck = x["source"] == source
    splitcheck = x["source_split"] == split
    return sourcecheck and splitcheck


def _build_instruction(output: str, speciality: str, template: Union[str, Template]) -> str:
    if isinstance(template, Template):  # MEDIQAL
        num_correct_answers = len(output.replace("\n", "").split(","))
        multiple_correct_answers = num_correct_answers > 1
        instruction = template.render(
            multiple_correct_answers=multiple_correct_answers,
            speciality=speciality
        )
    else:
        instruction = template
    return instruction


def build_instruction(
    output: str,
    speciality: str,
    template: Union[str, Template]
) -> Dict[str, str]:
    instruction = _build_instruction(output, speciality, template)
    return {"instruction": instruction}


def build_instruction_batched(
    output: str,
    speciality: str,
    template: Union[str, Template]
) -> Dict[str, List[str]]:
    function = partial(_build_instruction, template=template)
    instructions = map(lambda x: function(*x), zip(output, speciality))
    return {"instruction": list(instructions)}


def sample_examples(
    ds: Dataset,
    fewshot_template: Template,
    num_examples: int,
    instruction_map_kwargs: Dict[str, Any],
    seed: int,
    disable_tqdm: bool=False
) -> str:
    """
    Samples `num_examples` instances from the dataset `ds` to be used as few-shot examples.
    """
    if disable_tqdm:
        disable_progress_bars()
    ds_train_examples = ds.shuffle(seed=seed).take(num_examples).map(
        **instruction_map_kwargs
    )
    enable_progress_bars()
    question_list = [
        f"QUESTION {i + 1} : {q['question']}\nRÉPONSE {i + 1} : {q['output']}" \
            for i, q in enumerate(ds_train_examples)
    ]
    formatted_text = fewshot_template.render(
        question_list=question_list,
        num_examples=num_examples
    )
    return formatted_text


def resample_wrap(
    instruction: Union[str, Dict[str, str]],
    **kwargs
) -> Dict[str, List[Dict[str, str]]]:
    fewshot_interstitial_text = sample_examples(**kwargs)
    prompt_instance = instruction_to_prompt_completion(
        instruction=instruction,
        interstitial_text=fewshot_interstitial_text
    )
    return prompt_instance


def prompt_word_count_map_func(instance: Dict[str, str]) -> Dict[str, int]:
    return {"word_count": sum(len(turn["content"].split()) for turn in instance["prompt"])}


def prepare_and_write_output(
    data_dict: Dict[str, Any],
    output_fp: Union[str, Path],
    wc_map_kwargs: Dict[str, Any],
    max_wc: int,
    logger: RootLogger
):
    dataset_dict = DatasetDict(data_dict).map(**wc_map_kwargs)
    if max_wc:
        dataset_dict = dataset_dict.filter(
            lambda x: x["word_count"] <= max_wc,
            desc=f"Removing prompts longer than {max_wc} words"
        )
    logger.info("OUTPUT DATASET:\n%s\n-> writing out to %s", repr(dataset_dict), output_fp)
    dataset_dict.save_to_disk(output_fp)


def main():
    
    ## SETUP ##
    logger = basic_logger_init()
    args = parse_arguments()
    dataset_dir = Path(args.ds_dir)
    assert dataset_dir.exists(), f"{dataset_dir} not found"
    input_dir = dataset_dir / ("v" + str(args.dataset_version))
    if args.resample and args.workers > 1:
        logger.warning("Multiprocessing is not supported for example resampling; setting num_proc=0")
        setattr(args, "workers", 0)
    
    ## LOAD DATA ##
    logger.info("Loading dataset: %s", input_dir)
    ds = load_from_disk(input_dir)
    with open(args.template_path_instruction_fixed) as f:
        instruction_template_fixed = f.read()
    instruction_template_dynamic = get_instruction_template(args.template_path_instruction_dynamic)
    if args.target_task_type == "icl":
        fewshot_template = get_instruction_template(args.template_path_fewshot)
        suffix = f"-{args.nshot}shot"
    else:
        setattr(args, "resample", False)
        setattr(args, "nshot", None)
        suffix = ""

    ## PROCESSING FUNCTION PARAMETERS ##
    fmt_instruction_map_kwargs = {
        "desc": "Building instructions",
        "input_columns": ["output", "speciality"],
        "batched": args.map_bs > 1,
        "batch_size": args.map_bs,
    }
    fmt_prompt_map_kwargs = {
        "remove_columns": [
            "instruction",
            "speciality",
            "question",
            "output",
            "data_dir",
            "source",
            "source_split"
        ],
        "desc": "Building prompts",
        "num_proc": args.workers if args.workers > 1 else None
    }
    wc_map_kwargs = {
        "function": prompt_word_count_map_func,
        "desc": "Counting words"
    }
    out_f = partial(
        prepare_and_write_output,
        wc_map_kwargs=wc_map_kwargs,
        max_wc=args.max_word_count,
        logger=logger
    ) 
    source_name2instruction_template = {
        "MEDIQAL": instruction_template_dynamic,
        "FRENCHMEDMCQA": instruction_template_fixed
    }
    ds_fmt_output_dir = dataset_dir.parents[0] / "fmt" / args.target_task_type
    ds_fmt_output_fp = make_version_subdir_path(ds_fmt_output_dir, suffix=suffix, make=True)
    
    ## MAIN FUNCTION LOOP ##
    data_dict = {}
    for source, instruction_template in source_name2instruction_template.items():
        ff_eval = partial(filter_func, source=source)
        ds_eval_src = ds.filter(ff_eval, desc=source + " validation set")
        ff_train = partial(filter_func, source=source, split="train")
        ds_train_src = ds.filter(ff_train, desc="train examples")
        fmt_instruction_map_kwargs["function"] = partial(
            build_instruction_batched if fmt_instruction_map_kwargs["batched"] else build_instruction,
            template=instruction_template
        )
        if args.target_task_type == "sft":
            fmt_prompt_map_kwargs["function"] = instruction_to_prompt_completion
            ds_train_src_with_instructions = ds_train_src.map(**fmt_instruction_map_kwargs)
            ds_train_fmt = ds_train_src_with_instructions.map(**fmt_prompt_map_kwargs)
        elif args.resample:
            fmt_prompt_map_kwargs["function"] = partial(
                resample_wrap,
                ds=ds_train_src,
                fewshot_template=fewshot_template,
                num_examples=args.nshot,
                instruction_map_kwargs=fmt_instruction_map_kwargs,
                disable_tqdm=True,
                seed=args.seed
            )
        else:
            fewshot_interstitial_text = sample_examples(
                ds=ds_train_src,
                fewshot_template=fewshot_template,
                num_examples=args.nshot,
                instruction_map_kwargs=fmt_instruction_map_kwargs,
                seed=args.seed
            )
            fmt_prompt_map_kwargs["function"] = partial(
                instruction_to_prompt_completion,
                interstitial_text=fewshot_interstitial_text
            )
        ds_eval_src_with_instructions = ds_eval_src.map(**fmt_instruction_map_kwargs)
        ds_eval_fmt = ds_eval_src_with_instructions.map(**fmt_prompt_map_kwargs)
        if args.target_task_type == "icl":
            data_dict[source.lower()] = ds_eval_fmt
        else:
            out_f(
                data_dict={"train": ds_train_fmt, "validation": ds_eval_fmt},
                output_fp=ds_fmt_output_fp / source.lower()
            )
    if data_dict:
        out_f(data_dict=data_dict, output_fp=ds_fmt_output_fp)
    with (ds_fmt_output_fp / "script_params.json").open("w") as f:
        json.dump(vars(args), f, indent=4)


if __name__ == "__main__":
    main()

